"""Exporters and parity checks: ship exactly what was measured.

jev's production probes were generated byte for byte from the measured question
file, then production was checked against the lab (77.7% of training skills
flagged in production against 78.8% in the lab). Two checks make that routine:

* ``check_artifact``: the shipped file equals a fresh export of the measured
  probe set (byte for byte for code; same content hash for JSON).
* ``check_production``: production's verdicts on a split agree with the lab's,
  within a tolerance on recall and false-positive rate.

Exports embed the probe set's SHA-256, its threshold, model, state budget, every
question as sent, and a ``score`` function compiled from the score expression.
"""

from __future__ import annotations

import json
import re
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Mapping, Sequence

from skill_factory.classifier.dataset import Example
from skill_factory.classifier.metrics import Rates, rates
from skill_factory.classifier.probeset import ProbeSet, Score, describe_score

FORMATS = ("json", "ts", "py")
_SHA_RE = re.compile(r"\b([0-9a-f]{64})\b")
_HEADER = "Generated by skill-factory from probe set {name!r}. Do not edit: regenerate with `skill-factory lab export`."


def format_of(path: str | Path) -> str:
    suffix = Path(path).suffix.lower()
    fmt = {".json": "json", ".ts": "ts", ".mts": "ts", ".js": "ts", ".mjs": "ts", ".py": "py"}.get(suffix)
    if fmt is None:
        raise ValueError(f"cannot tell the export format of {path}; use .json, .ts or .py")
    return fmt


def export_probeset(probeset: ProbeSet, fmt: str) -> str:
    if fmt == "json":
        return json.dumps(probeset.to_dict(), indent=1, ensure_ascii=False) + "\n"
    if fmt == "ts":
        return _typescript(probeset)
    if fmt == "py":
        return _python(probeset)
    raise ValueError(f"unknown export format {fmt!r}; one of {', '.join(FORMATS)}")


def write_export(probeset: ProbeSet, path: str | Path, fmt: str | None = None) -> Path:
    p = Path(path)
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(export_probeset(probeset, fmt or format_of(p)), encoding="utf-8")
    return p


# --- TypeScript -----------------------------------------------------------

def _typescript(ps: ProbeSet) -> str:
    sha = ps.content_hash()
    q_lines = []
    for qid, q in ps.bank.compiled().items():
        q_lines += [
            f"  {_s(qid)}: {{",
            '    type: "choice",',
            f"    instructions: {_s(q.instructions)},",
            f"    criteria: {{ true: {_s(q.true)}, false: {_s(q.false)} }},",
            "  },",
        ]
    return "\n".join([
        f"// {_HEADER.format(name=ps.name)}",
        f"// sha256: {sha}",
        "",
        f"export const PROBESET_SHA256 = {_s(sha)};",
        f"export const MODEL = {_s(ps.model)};",
        f"export const PINNED_VERSION: string | null = {_s(ps.pinned_version) if ps.pinned_version else 'null'};",
        f"export const STATE_BUDGET = {ps.state_budget};",
        f"export const THRESHOLD = {_num(ps.threshold) if ps.threshold is not None else 'Number.NaN'};",
        "",
        "export interface ChoiceQuestion {",
        '  readonly type: "choice";',
        "  readonly instructions: string;",
        "  readonly criteria: { readonly true: string; readonly false: string };",
        "}",
        "",
        "export const QUESTIONS: Readonly<Record<string, ChoiceQuestion>> = {",
        *q_lines,
        "};",
        "",
        f"/** {describe_score(ps.score)}. NaN when a question it reads was not answered. */",
        "export function score(p: Readonly<Record<string, number>>): number {",
        f"  return {_ts_expr(ps.score)};",
        "}",
        "",
        "export function flags(p: Readonly<Record<string, number>>): boolean {",
        "  return score(p) >= THRESHOLD;",
        "}",
        "",
    ])


def _ts_expr(e: Score) -> str:
    if isinstance(e, str):
        return f"(p[{_s(e)}] ?? Number.NaN)"
    if isinstance(e, (int, float)):
        return _num(e)
    (op, arg), = e.items()
    if op == "mean":
        return f"(({' + '.join(_ts_expr(x) for x in arg)}) / {len(arg)})"
    if op == "sum":
        return f"({' + '.join(_ts_expr(x) for x in arg)})"
    if op in ("max", "min"):
        return f"Math.{op}({', '.join(_ts_expr(x) for x in arg)})"
    if op == "weighted":
        return f"({' + '.join(f'{_num(w)} * {_ts_expr(x)}' for w, x in arg)})"
    return f"({_ts_expr(arg[0])} * {_num(arg[1])})"


# --- Python ---------------------------------------------------------------

def _python(ps: ProbeSet) -> str:
    sha = ps.content_hash()
    q_lines = []
    for qid, q in ps.bank.compiled().items():
        q_lines += [
            f"    {_s(qid)}: {{",
            '        "type": "choice",',
            f'        "instructions": {_s(q.instructions)},',
            f'        "criteria": {{"true": {_s(q.true)}, "false": {_s(q.false)}}},',
            "    },",
        ]
    return "\n".join([
        f"# {_HEADER.format(name=ps.name)}",
        f"# sha256: {sha}",
        "",
        "import math",
        "",
        f"PROBESET_SHA256 = {_s(sha)}",
        f"MODEL = {_s(ps.model)}",
        f"PINNED_VERSION = {_s(ps.pinned_version) if ps.pinned_version else 'None'}",
        f"STATE_BUDGET = {ps.state_budget}",
        f"THRESHOLD = {_num(ps.threshold) if ps.threshold is not None else 'math.nan'}",
        "",
        "QUESTIONS = {",
        *q_lines,
        "}",
        "",
        "",
        "def _p(p, qid):",
        "    v = p.get(qid)",
        "    return math.nan if v is None else float(v)",
        "",
        "",
        "def _max(*xs):",
        "    return math.nan if any(math.isnan(x) for x in xs) else max(xs)",
        "",
        "",
        "def _min(*xs):",
        "    return math.nan if any(math.isnan(x) for x in xs) else min(xs)",
        "",
        "",
        "def score(p):",
        f'    """{describe_score(ps.score)}. NaN when a question it reads was not answered."""',
        f"    return {_py_expr(ps.score)}",
        "",
        "",
        "def flags(p):",
        "    return score(p) >= THRESHOLD",
        "",
    ])


def _py_expr(e: Score) -> str:
    if isinstance(e, str):
        return f"_p(p, {_s(e)})"
    if isinstance(e, (int, float)):
        return _num(e)
    (op, arg), = e.items()
    if op == "mean":
        return f"(({' + '.join(_py_expr(x) for x in arg)}) / {len(arg)})"
    if op == "sum":
        return f"({' + '.join(_py_expr(x) for x in arg)})"
    if op in ("max", "min"):
        return f"_{op}({', '.join(_py_expr(x) for x in arg)})"
    if op == "weighted":
        return f"({' + '.join(f'{_num(w)} * {_py_expr(x)}' for w, x in arg)})"
    return f"({_py_expr(arg[0])} * {_num(arg[1])})"


def _s(text: str) -> str:
    """A string literal valid in both TypeScript and Python."""
    return json.dumps(text, ensure_ascii=True)


def _num(x: float | int) -> str:
    return repr(float(x)) if isinstance(x, float) else str(int(x))


# --- parity ---------------------------------------------------------------

@dataclass(frozen=True)
class ArtifactParity:
    ok: bool
    expected_sha: str
    found_sha: str | None
    detail: str

    def summary(self) -> str:
        head = "artifact parity: OK" if self.ok else "artifact parity: MISMATCH"
        return f"{head} (measured {self.expected_sha[:12]}, shipped {(self.found_sha or 'no hash')[:12]}); {self.detail}"


def check_artifact(probeset: ProbeSet, path: str | Path, fmt: str | None = None) -> ArtifactParity:
    """Is the shipped file exactly what ``export`` makes of the measured probe set?"""
    p = Path(path)
    if not p.exists():
        raise FileNotFoundError(f"shipped artifact not found: {p}")
    fmt = fmt or format_of(p)
    actual = p.read_text(encoding="utf-8")
    expected_sha = probeset.content_hash()
    match = _SHA_RE.search(actual)
    found = match.group(1) if match else None
    if fmt == "json":
        try:
            data = json.loads(actual)
            if not isinstance(data, dict):
                raise ValueError("the file is not a JSON object")
            shipped = ProbeSet.from_dict({k: v for k, v in data.items() if k != "sha256"})
        except ValueError as exc:  # JSONDecodeError is a ValueError
            return ArtifactParity(False, expected_sha, found, f"not a probe set: {exc}")
        same = shipped.content_hash() == expected_sha
        return ArtifactParity(same, expected_sha, shipped.content_hash(),
                              "same questions, score, threshold, model and budget" if same
                              else "content differs from the measured probe set")
    expected = export_probeset(probeset, fmt)
    if actual == expected:
        return ArtifactParity(True, expected_sha, found, "byte for byte identical to a fresh export")
    return ArtifactParity(False, expected_sha, found, _first_difference(expected, actual))


def _first_difference(expected: str, actual: str) -> str:
    exp, act = expected.splitlines(), actual.splitlines()
    for i, (a, b) in enumerate(zip(exp, act), start=1):
        if a != b:
            return f"line {i} differs: expected {a[:120]!r}, shipped {b[:120]!r}"
    return f"lengths differ: expected {len(exp)} lines, shipped {len(act)}"


@dataclass(frozen=True)
class BehaviorParity:
    compared: int
    agree: int
    missing: int
    lab: Rates
    production: Rates
    disagreements: tuple[tuple[str, bool, bool], ...]
    tolerance: float

    @property
    def ok(self) -> bool:
        return (
            self.compared > 0
            and abs(self.lab.recall - self.production.recall) <= self.tolerance
            and abs(self.lab.fpr - self.production.fpr) <= self.tolerance
        )

    def summary(self) -> str:
        return (
            f"behavior parity: {'OK' if self.ok else 'MISMATCH'} on {self.compared} examples "
            f"({self.agree / max(1, self.compared):.1%} agree, {self.missing} missing from production); "
            f"recall lab {self.lab.recall:.1%} vs production {self.production.recall:.1%}, "
            f"FPR lab {self.lab.fpr:.2%} vs production {self.production.fpr:.2%} "
            f"(tolerance {self.tolerance:.1%})"
        )


def load_production(path: str | Path) -> list[dict[str, Any]]:
    rows = []
    for lineno, line in enumerate(Path(path).read_text(encoding="utf-8").splitlines(), start=1):
        if line.strip():
            try:
                rows.append(json.loads(line))
            except json.JSONDecodeError as exc:
                raise ValueError(f"{path}:{lineno}: invalid JSON: {exc}") from exc
    return rows


def check_production(
    examples: Sequence[Example],
    lab_detected: Mapping[str, bool],
    production_rows: Sequence[Mapping[str, Any]],
    *,
    detect_levels: Sequence[str] = ("flag",),
    threshold: float | None = None,
    tolerance: float = 0.02,
) -> BehaviorParity:
    """Compare production's detections with the lab's on the same examples.

    A production row is ``{"id", "verdict"}`` (detected when the verdict is one of
    ``detect_levels``), ``{"id", "flagged": bool}``, or ``{"id", "score"}`` with
    ``threshold``.
    """
    prod: dict[str, bool] = {}
    for row in production_rows:
        if "id" not in row:
            raise ValueError("every production row needs an 'id'")
        prod[str(row["id"])] = _detected(row, detect_levels, threshold)
    labels, lab_flags, prod_flags, disagreements = [], [], [], []
    missing = 0
    for ex in examples:
        if ex.id not in prod:
            missing += 1
            continue
        labels.append(ex.label)
        lab_flags.append(lab_detected[ex.id])
        prod_flags.append(prod[ex.id])
        if lab_detected[ex.id] != prod[ex.id]:
            disagreements.append((ex.id, lab_detected[ex.id], prod[ex.id]))
    return BehaviorParity(
        compared=len(labels),
        agree=len(labels) - len(disagreements),
        missing=missing,
        lab=rates(labels, lab_flags),
        production=rates(labels, prod_flags),
        disagreements=tuple(disagreements),
        tolerance=tolerance,
    )


def _detected(row: Mapping[str, Any], levels: Sequence[str], threshold: float | None) -> bool:
    if "flagged" in row:
        return bool(row["flagged"])
    if "verdict" in row:
        return str(row["verdict"]) in levels
    if "score" in row:
        if threshold is None:
            raise ValueError("production rows carry scores; a threshold is needed")
        return row["score"] is not None and float(row["score"]) >= threshold
    raise ValueError(f"production row {row.get('id')!r} has no verdict, flagged or score")
